INSERT INTO SHELTER(SHELTER_ID, SHELTER_NAME, LOCATION, EMAIL, IS_ACTIVE) VALUES (1001, 'Debreceni Menhely', 'Debrecen', 'debrecenimenhely@email.hu', true);
INSERT INTO SHELTER(SHELTER_ID, SHELTER_NAME, LOCATION, IS_ACTIVE) VALUES (1002, 'Nyíregyházi Menhely', 'Nyíregyháza', true);
INSERT INTO SHELTER(SHELTER_ID, SHELTER_NAME, LOCATION, EMAIL, IS_ACTIVE) VALUES (1003, 'Budapesti Menhely', 'Budapest', 'budapestimenhely@email.com', true);
INSERT INTO SHELTER(SHELTER_ID, SHELTER_NAME, LOCATION, IS_ACTIVE) VALUES (1004, 'Kaposvári Menhely', 'Kaposvár', false);

INSERT INTO DOG(DOG_ID, DOG_NAME, BREED, BIRTH_YEAR, GENDER, SHELTER_ID, IS_AVAILABLE_FOR_ADOPTION) VALUES (101, 'Buksi', 'keverék', 2021, 1, 1001, true);
INSERT INTO DOG(DOG_ID, DOG_NAME, BIRTH_YEAR, GENDER, SHELTER_ID, IS_AVAILABLE_FOR_ADOPTION) VALUES (102, 'Füles', 2023, 1, 1001, true);
INSERT INTO DOG(DOG_ID, DOG_NAME, BREED, BIRTH_YEAR, GENDER, SHELTER_ID, IS_AVAILABLE_FOR_ADOPTION) VALUES (103, 'Szója', 'keverék', 2019, 0, 1001, false);
INSERT INTO DOG(DOG_ID, DOG_NAME, GENDER, SHELTER_ID, IS_AVAILABLE_FOR_ADOPTION) VALUES (104, 'Maci', 1, 1002, true);
INSERT INTO DOG(DOG_ID, DOG_NAME, BREED, BIRTH_YEAR, GENDER, SHELTER_ID, IS_AVAILABLE_FOR_ADOPTION) VALUES (105, 'Buksi', 'labrador', 2021, 0, 1003, true);
